# Configuration for Alacritty, the GPU enhanced terminal emulator.
#Defaults file path:    /usr/share/doc/alacritty/example/alacritty.yml
env:
  TERM: xterm-256color

colors:
  primary:
    background: '#0c0c0c'
    foreground: '#2ec600'
    dim_foreground: '#828482'
    bright_foreground: '#eaeaea'

  cursor:
    text: '#FED2EC'
    cursor: '#2ec600'

    bar:
      background: '#c5c8c6'
      foreground: '#1d1f21'


font:
  normal:
    family: fira mono
    style: Regular

  bold:
    family: fira mono
    style: Bold

  italic:
    family: fira mono
    style: Italic

  bold_italic:
    family: fira mono
    style: Bold Italic

  size: 14


window:
  title: Alacritty
  dynamic_title: true


key_bindings:
  - { key: V, mods: Control, action: Paste }
  - { key: C, mods: Control, action: Copy }

