# MQTT settings
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: "mqtt://172.17.0.1"
  #server: 'mqtt://localhost'
  #server: "mqtt://172.17.0.1"
  #server: "mqtt://192.168.0.196:1883"
  #http://192.168.0.196:8089/
  #server: mqtt://mqtt
  #server: 'mqtt://localhost'
  #server: 'mqtt://localhost:1883'
  #user:
  #password:

# Serial settings
serial:
  # USB adapters - use format "port: /dev/ttyACM0"
  # To autodetect the USB port, set 'port: null'.
  port: /dev/ttyACM0
  #disable_led: false
  # Optional: adapter type, not needed unless you are experiencing problems (default: shown below, options: zstack, deconz, ezsp)
  #adapter: null
  # Optional: Baud rate speed for serial port, this can be anything firmware support but default is 115200 for Z-Stack and EZSP, 38400 for Deconz, however note that some EZSP firmware need 57600.
  #baudrate: 115200
  # Optional: RTS / CTS Hardware Flow Control for serial port (default: false)
  #rtscts: false

frontend:
  port: 8080

#advanced:
  #network_key: GENERATE
