---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Development:
  - Github:
    - icon: github.png
      href: https://github.com/

  - ChatGPT:
    - icon: chatgpt.png
      href: https://chat.openai.com/

- Leisure:
  - Reddit:
    - icon: reddit.png
      href: https://reddit.com/

  - YouTube:
    - icon: youtube.png
      href: https://www.youtube.com/feed/library

- Streaming:
  - Netflix:
    - icon: netflix.png
      href: https://www.netflix.com/browse

  - HBOMax:
    - icon: reddit.png
      href: https://play.hbomax.com/signIn

- Communication:
  - Whatsapp:
    - icon: whatsapp.png
      href: https://web.whatsapp.com/

  - Teleram:
    - icon: telegram.png
      href: https://web.telegram.org/k/

- Cloud Storage:
  - GoogleDrive:
    - icon: google.png
      href: https://drive.google.com/drive/my-drive

  - OneDrive:
    - icon: microsoft.png
      href: https://www.office.com/?auth=1
