---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks



- Development:
  - Github:
    - icon: reddit.png
      href: https://github.com/

  - ChatGPT:
    - icon: reddit.png
      href: https://chat.openai.com/

- Leisure:
  - Reddit:
    - icon: reddit.png
      href: https://reddit.com/

  - YouTube:
    - icon: reddit.png
      href: https://www.youtube.com/feed/library

  - Netflix:
    - icon: reddit.png
      href: https://www.netflix.com/browse

  - HBOMax:
    - icon: reddit.png
      href: https://play.hbomax.com/signIn
