---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Github:
  - abbr: GH
    href: https://github.com/

- ChatGPT:
  - abbr: GPT
    href: https://chat.openai.com/

- Reddit:
  - abbr: RE
    href: https://reddit.com/

- YouTube:
  - abbr: YT
    href: https://www.youtube.com/feed/library

