---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: Home Server
headerStyle: boxed
target: _blank

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

#background:
  #image: /images/grubbootloaderpic.png
  #blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  #saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  #brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  #opacity: 50 # 0-100

theme: dark # or light

#slate, gray, zinc, neutral, stone, amber, yellow, lime, green, emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white
color: lime

layout:
  Home Server:
    style: row
    columns: 3
  Debian Server:
    style: row
    columns: 3
