---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    uptime: true
    units: metric

- openmeteo:
    label: Cluj
    latitude: 46.7693
    longitude: 23.5842
    timezone: Europe/Bucharest # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits

- search:
    provider: google # google, duckduckgo, bing, baidu, brave or custom
    focus: true # Optional, will set focus to the search bar on page load
    target: _blank # One of _self, _blank, _parent or _top


- datetime:
    text_size: xl
    format:
        timeStyle: short # long
        dateStyle: short # long
        hourCycle: h23 #  hour12: true
